### ISSUE TITLE
Add direct link to evolution view to alerts

### ISSUE THREAD

**Issue by chutten** [mozilla/medusa#21]
I usually end up looking at the evolution view dashboard to check out any regressions.
Can we get a direct link to it in the mail?
Currently getting there requires a lot of steps: click link in mail -> find and click link to get to distribution view -> click evolution view -> wait for loading...

Clone of mozilla/cerberus#30

**Comment by erikrose** [comment]
Maybe https://docs.telemetry.mozilla.org/tools/alerts.html would be useful background.

**Comment by erikrose** [comment]
#25 would make sense to do at the same time.

**Comment by chutten** [comment]
This was taken care of by #25
