### ISSUE TITLE
Add "Next Steps" to Alert Emails

### ISSUE THREAD

**Issue by chutten** [mozilla/medusa#25]
People receiving alert emails don't necessarily know what to do with them. The email itself should include instructions.

Maybe something similar to the Triage segment here https://docs.telemetry.mozilla.org/tools/alerts.html

**Comment by georgf** [comment]
It would probably be good to have a short, concrete list of steps in the email (so it actually gets read).
You could link to the triage section for more details: https://docs.telemetry.mozilla.org/tools/alerts.html#triaging-a-telemetry-alert-email

**Comment by chutten** [comment]
How's this:

Subject: Telemetry Alert for PROBE_NAME on yyyy-mm-dd

We have detected a change in the Telemetry Probe PROBE_NAME in Nightly builds from yyyy-mm-dd. 

You can view the alert here: <alerts.tmo>
A list of changes new to Nightly builds that day are here: <hg.mo>
You can view the value of this probe over time here: <tmo/evo>

What To Do About This:

The first and most important task is to reply-all to this email to let the list know that you are investigating. That will stop us from duplicating your efforts while you look into this. If you take investigation to a bug, or stop investigating, please reply-all again with that information.

The next thing to do is triage the alert so we get to the bottom of what code change in particular caused this alert, and how much we should worry about it. You can find instructions on how to triage an alert here: https://docs.telemetry.mozilla.org/tools/alerts.html#triaging-a-telemetry-alert-email

If you have any problems, please do ask for help on the #telemetry IRC channel. We'll give you a hand.

You can do this!

Your Friendly, Neighbourhood Firefox Telemetry Team

**Comment by chutten** [comment]
@georgf @fbertsch @Dexterp37 @badboy @erikrose What do you think^

**Comment by fbertsch** [comment]
@chutten I think it might be a good idea to have a checklist under "What to do about this". That's easy to follow for people.

I might recommend adding a section like the following (at the bottom though, so people focus on the "What to do" section:

What Is This:
Our system compared builds on `yyyy-mm-dd` to builds on `yyyy-mm-dd - interval 1 day`. Using the Batacharyyan distance (link needed), it found a difference between builds on those two days.

**Comment by Dexterp37** [comment]
@chutten @fbertsch what about strongly suggesting to file a bug? We may provide a template for the information we need. This might be helpful for the golden dataset work, I think: it would allow easier scraping :)

**Comment by erikrose** [comment]
Looks great, @chutten! Here, I just concisened the link labels a bit so they're more scannable:

The alert itself: <alerts.tmo>
A list of changes new to Nightly builds that day: <hg.mo>
The value of this probe over time: <tmo/evo>

**Comment by chutten** [comment]
Okay, folding in the feedback, how about:

---

Subject: Telemetry Alert for PROBE_NAME on yyyy-mm-dd

We have detected a change in the Telemetry Probe PROBE_NAME in Nightly builds from yyyy-mm-dd.

The alert itself: <alerts.tmo>
A list of changes new to Nightly builds that day: <hg.mo>
The value of this probe over time: <tmo/evo>

What To Do About This:
1. File a bug to track your investigation. You can just copy this email into the Description to get you started.
2. Reply-All to this email to let the list know that you are investigating and include the bug number so we can help out in case we know anything about the alert.
3. Triage the alert. You can find instructions here: https://docs.telemetry.mozilla.org/tools/alerts.html#triaging-a-telemetry-alert-email

If you have any problems, please ask for help on the #telemetry IRC channel. We'll give you a hand.

What is This:
We have a system called cerberus`[1]` that compares Telemetry collected on different Nightly builds and looks for sudden changes in value distributions using the Bhattacharyya Distance`[2]`. It found such a change in PROBE_NAME on yyyy-mm-dd so it asked its buddy medusa`[3]` to send this email to the dev-telemetry-alerts mailing list and to all email addresses listed in the alert_emails field of PROBE_NAME's definition.

You can do this!

Your Friendly, Neighbourhood Firefox Telemetry Team

`[1]: https://github.com/mozilla/cerberus`
`[2]: https://en.wikipedia.org/wiki/Bhattacharyya_distance`
`[3]: https://github.com/mozilla/medusa`

**Comment by chutten** [comment]
@georgf @fbertsch @Dexterp37 @badboy @erikrose ^

**Comment by fbertsch** [comment]
@chutten there's a spelling error, it is `Neighborhood`. Other than that r+!

**Comment by erikrose** [comment]
Lgtm! Feel free to change "The alert itself" to something less pointy; I know I wrote it, but now I don't like it. :-)

**Comment by georgf** [comment]
Nice, this looks great!

I'd tweak the link descriptions a little to be more descriptive to users and tweak the order:
> See a list of code changes to Nightly builds on this day: <hg.mo>
> See how the value of this probe developed over time: <tmo/evo>
> See more details on this alert: <alerts.tmo>

This turns this more into "action descriptions" and moves the alert details last (as i assume this is not the primary action users are looking for).

**Comment by georgf** [comment]
Could you put an example of this text with actual working links in front of an engineer (in person in SF or on Vidyo) and have them explore / work through it?
Listen in, take notes and see if anything stands out.

**Comment by georgf** [comment]
> If you have any problems, please ask for help on the #telemetry IRC channel. We'll give you a hand.

Or on Slack in #fx-metrics?

**Comment by chutten** [comment]
> This turns this more into "action descriptions" and moves the alert details last (as i assume this is not the primary action users are looking for).

The alert's the first place to start as it may be the only place you can easily tell what has changed. Our evolution view may not capture the change clearly, so I (at least) rely on it to show me what the change was and where to focus my investigation.

> Could you put an example of this text with actual working links in front of an engineer (in person in SF or on Vidyo) and have them explore / work through it?
> Listen in, take notes and see if anything stands out.

You're right, being at the All Hands affords me an audience to study. I'll see if I can fit this in.

**Comment by georgf** [comment]
> > This turns this more into "action descriptions" and moves the alert details last (as i assume this is not the primary action users are looking for).
> 
> The alert's the first place to start as it may be the only place you can easily tell what has changed. Our evolution view may not capture the change clearly, so I (at least) rely on it to show me what the change was and where to focus my investigation.

Ok, i personally was never able to understand what the alert details want to tell me.
But this is a big improvement anyway, so let's not bikeshed on this!

**Comment by chutten** [comment]
Feedback from wlach:

* Use fewer words if we can get away with it
* This is a large improvement over what we have, so maybe just ship it ("perfect" is the enemy of "good")
* Can we get a text description of the change into the email itself? (No, or at least not without a lot of engineering)
* There are interesting parallels with perfherder talos alerts/bug templates
* The links are good
* :jmaher deals with this a lot, maybe we should seek out his input, too? (couldn't find him just now. Will keep eyes peeled)
