### ISSUE TITLE
Some detected regressions aren't being emailed

### ISSUE THREAD

**Issue by chutten** [mozilla/medusa#27]
I noticed when perusing the logs that there were regressions I didn't remember being emailed about.

For instance, in cerberus' `regressions.json` there is a 2018-01-11 record for `UPDATE_STATE_CODE_PARTIAL_STARTUP` and I received no email for that. I have received alerts before and since, but not that one (and others).

I checked medusa's frontend and it's on the webpage: http://alerts.telemetry.mozilla.org/index.html#/detectors/1/metrics/1231/alerts/?from=2017-12-23&to=2018-01-23&metrics-filter=

But it's not anywhere in the list archives that I can find: https://groups.google.com/forum/#!forum/mozilla.dev.telemetry-alerts

Something is wrong :S

**Comment by erikrose** [comment]
There's nothing in /var/log/medusa.out.log after Jan 4. There's nothing in medusa.err.log between Jan 8 and Jan 15, exclusive. Given that `(log/info "Changeset URL" changeset-url)` and `(log/info e "Retrieving changeset failed")` happen before any attempt at sending a mail, it appears Medusa never even tried to send those mails. It occurred to me that maybe the box didn't come up properly after the Meltdown/Spectre reboots (some communication path between Cerberus and Medusa getting hosed?), except that [a Jan 19 alert](https://groups.google.com/forum/#!topic/mozilla.dev.telemetry-alerts/CNhetyXU7jI) went out fine. Hmm. More as it develops.

**Comment by erikrose** [comment]
In all, we're missing alert emails from 2018-01-10, 2018-01-11, and 2018-01-13. The one from 2018-02-01 went out fine.

Actually, that's not all at all. There seems to be a long-running problem with mails going out late:

* 2017-12-04 alert went out on 2018-01-08.
* 2017-12-05 on 2017-12-20
* 2017-12-06 on 2017-12-19
* 2017-12-03 on 2017-12-07
* 2017-12-08 on 2017-12-21

Actually actually, my spot-checking back to 9/2017 doesn't find a single mail that went out when it was labeled. Do the JSON keys mean what we think they mean, or are they just the dates of the first samples or something?

**Comment by erikrose** [comment]
We looked at the SES logs, and they do show 1 bounce for 2018-01-17, which is one for which we have a log line in /var/log/medusa.err.log but no corresponding mail. SES doesn't give us any more detail than the count. I'll see if I can find a synchronous SES API to call instead that'll give us more detailed errors we can log.

**Comment by erikrose** [comment]
2 things to do:
* Log any HTTP error coming back from the ses/send-email call.
* Set the [ReturnPath param](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html) of the call so any bounces come back to us via mail. "This email address must be either individually verified with Amazon SES, or from a domain that has been verified with Amazon SES," so we'll have to make sure that's the case.

**Comment by erikrose** [comment]
Waiting for confirmation of a verified address we can use for bounces or for SES creds so I can do it myself.

**Comment by fbertsch** [comment]
@erikrose looks like `telemetry-alerts@mozilla.com` is verified with ses. I think that's all you need from me?

**Comment by chutten** [comment]
Where does that email go? Does it post to the dev-telemetry-alerts list?

**Comment by erikrose** [comment]
@fbertsch So you verified that particular address and not the whole mozilla.com domain? Okay, then we should probably make a "telemetry-bounces" alias or something at mozilla.com and verify that one as well. I'll look into it.

**Comment by fbertsch** [comment]
@erikrose right - let me know and I can add telemetry-bounces to that list as well.

**Comment by erikrose** [comment]
@fbertsch I made telemetry-alert-bounces at mozilla.com. Have at it!

**Comment by fbertsch** [comment]
@erikrose anddddd it is verified!

**Comment by erikrose** [comment]
After reading the SES Java SDK source and the dynamic Clojure lib, Amazonica, which wraps it, I see that Thing Number 1, logging any HTTP error coming back from the SES `send-email` call, is effectively already done: errors are modeled as exceptions, which are already logged. (The only thing `send-email` returns is a thin object containing a messageId—no error component.)

**Comment by erikrose** [comment]
Added a return path, completing Thing Number 2 above, in 44e3ba28bfb72156171c98723c2394d1486070bf. And deployed. Now let's see if we receive any answers.

**Comment by erikrose** [comment]
No notification of bounces via email yet. One alert mail [was received by a Mozillian](https://bugzilla.mozilla.org/show_bug.cgi?id=1454668#c15), and "To: kgupta@mozilla.com, dev-telemetry-alerts@lists.mozilla.org" was in the headers, so medusa is at least setting the headers correctly. The mail was logged properly in medusa.err.log (yes, not info.log). Actually, there were 3 matching log entries, all in medusa.err.log, all on Apr 21 5:54 server time, a few seconds apart. "Is something going awry between SES and the Google Group mail servers?" chutten and I wonder.

**Comment by erikrose** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1456144 to see if the mails are getting hung up at lists.m.o.

**Comment by erikrose** [comment]
Closed via https://bugzilla.mozilla.org/show_bug.cgi?id=1456144.
