### ISSUE TITLE
Document how to deploy changes

### ISSUE THREAD

**Issue by chutten** [mozilla/medusa#35]
From `git pull --rebase` to `supervisor> restart medusa` we would benefit from a step-by-step guide in the README about how to deploy changes to medusa.

**Comment by chutten** [comment]
@erikrose Do you want to take this one?

**Comment by erikrose** [comment]
The reason I haven't written it up definitively is that I suspect there's a nicer way, through the ansible playbooks already in the codebase. However, the quick-and-dirty-but-it-sure-works method I've been using is the following:

```
git pull --ff-only ...
sudo lein cljsbuild once release
sudo supervisorctl
supervisor> restart medusa
```
