### ISSUE TITLE
Add Bugzilla integration

### ISSUE THREAD

**Issue by vitillo** [mozilla/medusa#8]
It would be nice to integrate the medusa dashboard with Bugzilla. 

The current workflow requires a human to look at new regressions and if needed to file a bug for it on Bugzilla. The medusa dashboard should ideally provide an option to file a new bug for a regression and keep track of its status.

**Comment by chutten** [comment]
For now we're looking at how mission control will handle alerting and filing issues. Any changes to medusa will likely be direct clones of whatever is decided by mission control as it has proper Project/Program support.
